export class RechazoSintaxis {

  public dtFechaProceso: string;
  public iNoLote: number;
  public mImpTxn: number;
  public mMontoRet: number;
  public vArqc: string;
  public vCodEmi: string;
  public vCodErr: string;
  public vCodRiesgo: string;
  public vCodServicio: string;
  public vCodTra: string;
  public vCompleAut: string;
  public vCtroReg: string;
  public vDifPromo: string;
  public vEstatus: string;
  public vExtAutoriza: string;
  public vFeCaptura: string;
  public vFeExpira: string;
  public vFeTxn: string;
  public vHorTtxn: string;
  public vIdAdq: string;
  public vIdBonus: string;
  public vIdEmi: string;
  public vIdTerminal: string;
  public vIndRedCel: string;
  public vInstCode: string;
  public vInstIdCode: string;
  public vNoAfiliacion: string;
  public vNoPlastico: string;
  public vNoSerieTerminal: string;
  public vNumAutoriza: string;
  public vNumBatchterm: string;
  public vNumRef: string;
  public vNumTxnTerm: string;
  public vParcializ: string;
  public vPlataforma: string;
  public vPosEntryMode: string;
  public vRegLlave: string;
  public vRrn: string;
  public vStatusFlujo: string;
  public vStatusServer: string;
  public vTipPlan: string;
  public vTipoReg: string;
  public vTrmlCapability: string
} 